name: Release image

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      push:
        type: boolean
        default: true
    secrets:
      token:
        required: true

jobs:
  release:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,mode=max
